// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var $$String = require("bs-platform/lib/js/string.js");

var StringMap = $$Map.Make([$$String.compare]);

exports.StringMap = StringMap;
/* StringMap Not a pure module */
