// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Schema$ReasonGraphqlServer = require("./Schema.bs.js");

var datetime = Schema$ReasonGraphqlServer.scalar(undefined, (function (input) {
        if (typeof input === "number" || input[0] !== -976970511) {
          return Pervasives.failwith("Not a valid date");
        } else {
          return new Date(input[1]);
        }
      }), (function (date) {
        return /* `String */Block.polyVar("String", [
                  -976970511,
                  date.toDateString()
                ]);
      }), "DateTime");

var personObject = Schema$ReasonGraphqlServer.obj(undefined, undefined, (function (person) {
        return /* :: */Block.simpleVariant("::", [
                  Schema$ReasonGraphqlServer.field(undefined, undefined, (function (p) {
                          return p[/* name */0];
                        }), "name", Schema$ReasonGraphqlServer.string),
                  /* :: */Block.simpleVariant("::", [
                      Schema$ReasonGraphqlServer.field(undefined, undefined, (function (p) {
                              return p[/* age */1];
                            }), "age", /* Nullable */Block.variant("Nullable", 4, [Schema$ReasonGraphqlServer.$$int])),
                      /* :: */Block.simpleVariant("::", [
                          Schema$ReasonGraphqlServer.field(undefined, undefined, (function (p) {
                                  return p[/* children */2];
                                }), "children", /* List */Block.variant("List", 1, [person])),
                          /* :: */Block.simpleVariant("::", [
                              Schema$ReasonGraphqlServer.field(undefined, undefined, (function (p) {
                                      return p[/* birthday */3];
                                    }), "birthday", datetime),
                              /* [] */0
                            ])
                        ])
                    ])
                ]);
      }), "person");

exports.datetime = datetime;
exports.personObject = personObject;
/* datetime Not a pure module */
