// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Parser$ReasonGraphqlServer = require("./Parser.bs.js");
var Printer$ReasonGraphqlServer = require("./Printer.bs.js");

var query = "\n  query MyQuery($id: Int, $another: [String!]!) { field {\n               hello: name\n      # Commentsssss\n               age(default: 4.5, a: [4, 5, 5])\n      ... on Foo {\n              bar(h: { hello: 5, nested: { world: 1} })\n                    ... on BarType {\n              baz    @skip(if: $another) @skip(if: $another)\n              ...bazFields\n      }\n      }\n    }\n  }\n\n  fragment bazFields on FragmentModel {\n    foo\n    baz {\n               g @skip(if: $another)\n      ... on Bar {\n        # dfffdfdfd\n        b @skip(if: $another) @skip(if: {a: [1, 3, 4]})\n                c\n          a\n      }\n    }\n  }\n";

console.log(Caml_obj.caml_equal("dfdf", "abc"));

console.log(query);

var $$document = Parser$ReasonGraphqlServer.parse(query);

console.log(Printer$ReasonGraphqlServer.print($$document));

exports.query = query;
exports.$$document = $$document;
/*  Not a pure module */
